apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-github-token
  namespace: renovate
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: renovate-github-token
    creationPolicy: Owner
  data:
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: renovate/RENOVATE_TOKEN

