apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: renovate
spec:
  schedule: "0 9 * * 6"  # 9am every Saturday Melbourne time
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: renovate
              image: renovate/renovate:latest
              args: ["cassiechew/homelab"]
              env:
                - name: RENOVATE_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: renovate-github-token
                      key: RENOVATE_TOKEN
                - name: RENOVATE_CONFIG_FILE
                  value: /usr/src/app/config.js
                - name: LOG_LEVEL
                  value: info
              resources:
                requests:
                  memory: 128Mi
                  cpu: 100m
                limits:
                  memory: 512Mi
                  cpu: 500m
              volumeMounts:
                - name: config
                  mountPath: /usr/src/app/config.js
                  subPath: config.js
          volumes:
            - name: config
              configMap:
                name: renovate-config

