apiVersion: v1
kind: Service
metadata:
  name: nas
  namespace: nas
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80   # Kubernetes internal port
      targetPort: 5001  # NAS Jellyfin port
