apiVersion: v1
kind: Service
metadata:
  name: nas
  namespace: nas
spec:
  type: ClusterIP
  ports:
    - name: http-nas
      protocol: TCP
      port: 5001   # Kubernetes internal port
      targetPort: 5001  # NAS port
