apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nas
  namespace: nas
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/acme-challenge-type: http01
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  rules:
    - host: nas.czcx.cc
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nas
                port:
                  number: 5001
