apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nas
  namespace: nas
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"  # Redirect HTTP to HTTPS
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"

spec:
  ingressClassName: nginx
  rules:
    - host: nas.internal.czcx.cc
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nas
                port:
                  number: 5001
  tls:
    - secretName: nas-internal-tls-prod-cert
      hosts:
        - nas.internal.czcx.cc