---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pocket-id-secret
  namespace: pocket-id
spec:
  encryptedData:
    ENCRYPTION_KEY: AgCjtsfG9jhL+6sjX/fqlsN965e3qh+IW5wYK/gn4kPmQmy9bLduLAsyNjXQBA9XJkN29dx3WWTqRKq3Kb4hS0EtfOSlLheY/7z7R+mLdEcj5jj73g0lhKi6c04tTKrN7g5CZRYwp3LHsljY48c8Ac++QOWy9K3fepJtlvjjz6iN/vSCI7dei3izwD10cdlqlZvtFv7y5lrMhhViSjhBovbT80DrqqM+9cGiuhtecE8IXd+PNWvkLhnu0bDXOaFUfsFIrhC92YbHDeyhEmm8i5NVTzqgtQ97gCJT9VJbUs5UnDd6obcMV4IEuOsb1Kxe5VCDJDppghCO4/QfVvckZXIq/eqWgdTI+spsRlpWIfKrK9s4XGb4WpYPCpYkWRUuc8tuxO81549FxgA9qJYGBMjScNxuCBWSXYnrN8JCskGlNxHSGOFcaYgYEuL1/VFt0AgIeVb9IKfJ+jFGffFqRvs1Uuc8VkDtdER1ufl3MyeedxQoz3AdZKQGxOLF0PuceUwC+g/IRQ1PCWdSv+is341AHRSp+3esUXzggznSVuImcoGK3hieyTGvP9m1ZwBjXGHE4JQVUfyKveASu1TT0NLqKizTexviFWLn/PrdPH4HlaDIAUW8PoP2izFqoKVZRJKpEFJK+YhLeQrQeTEfFeEtUmCXhaNNDgA0IVD7gEg6HIx9nBvc/x4UGzSjUf3qIGUhrpeJ4F7vH7QyeR0AXG/kKj+BscGhRi9I52flO/chMSyPvz3/XJsuZKKdWEPFKqUPplB6pJemgfEe+usRHJex
  template:
    metadata:
      name: pocket-id-secret
      namespace: pocket-id
