---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oidc
  namespace: monitoring
spec:
  encryptedData:
    client_secret: AgDIlbSnNAUjJzNDaA2GrdgWb+ixWS0T1kA+ppJogtXAjq5gUaLb7HWyR+ead8fVJ2/kDsL080OMaJMqY/gjoOUkQU+Z5c7TH0Uxx83RaS6QGWTRuo9PBOfq2K/GEqYZVbYjLoDquvHoYCdoVK/woe1KFfqmp+YYJv9fhC0Vqz/uE+Ij19OUfrjK97sT4r/jpd1rzZwfPwbxKr7IpX2f6Z+pKsVgOFebvGPGpjXbosrP39ARzfkbskH7ew3Y9eaiqt0WXu7M5xAk7xDUTDFOtb3rFN7CzH2/7jHc/Mlltb1Y1FCRywxvWME/KABpf50kZnM3uBi/EJYPws9Rbu2HRDWJ2lHITlAnMizGKCNlN5vK56lrlIp06cQbUVlx0uEyprAtnp55QH5eHgnZsnt0CcEEpUllbFxSszh+VMhwV4TJ7vFkeKYCfSS/mfLHzMCTT1U7b0b26tK1X2Hd9107S0XWohQRbLZmaTFfm5V3dPhupPPQAHhBNLFqYpGxC+9R2E4ZH/EILp5fWAwzXjfTqSeauD5+4B+1kk5mYSypsa5TdlLCZRuCI15D1EQ48ebe0KjJSUA2LUhuQkqPeCFBd4Dj/hM0OXoW6VP4gtFqyHoDPRgOSHdt3LWYkjSw/OURb+2jN5A6FsjTaBfW6mtllFxx21CN1VvoCDBqCm/6uTXGQmuG8x5NCTL4N5ZDtcBKGt7vKBT7WuF+CLUbm1YpGckLqpGT6/rKeph8DB9cmJI87w==
  template:
    metadata:
      name: grafana-oidc
      namespace: monitoring
