apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oidc
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: grafana-oidc
    creationPolicy: Owner
  data:
    - secretKey: client_secret
      remoteRef:
        key: grafana/client_secret
