apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls-prod-cert
  namespace: monitoring
spec:
  secretName: grafana-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - grafana.czcx.cc
