apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: observability
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
    exporters:
      otlphttp:
        endpoint: http://jaeger-collector.observability.svc.cluster.local:4318
        tls:
          insecure: true
      logging:
        loglevel: debug   
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [otlphttp, logging]