apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: grafana
data:
  grafana.ini: |
    [server]
    domain = grafana.czcx.cc
    root_url = %(protocol)s://%(domain)s/
    serve_from_sub_path = true
    [security]
    admin_user = admin
    admin_password = admin
