apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
data:
  grafana.ini: |
    [server]
    domain = grafana.czcx.cc
    root_url = %(protocol)s://%(domain)s/
    serve_from_sub_path = true
    [security]
    admin_user = admin
    admin_password = admin
  prometheus-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus.prometheus.svc.cluster.local:80
        access: proxy
        isDefault: true
