apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  selector:
    app: grafana
  ports:
    - name: http-grafana
      protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
