---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oauth2-proxy-secret
  namespace: observability
spec:
  encryptedData:
    client_secret: AgBfitM6jjoYICh2qrNM4hoigMyqnQbOL0utkJaNnrW0aIXyeVizpHc/idjuT4ptrj90iaFVh3uESTUpgAEmcixKUHlUNnKJunZFg7n6jHlJizExyeoMH+CJ7ukn5/8kFWN1oTEJeht1n0BPuEunk/F8cyegAHNC9ghNPvwwLOKNJ5lPjqV23CS9v6Kh9FV+6pnyIJfFkpe3ieJmXxc6tgHVIDz0yC7Ie/dRNXoQ4g5nkHnQl/O0skImuaR6l2Nqtr77cpoKmT0eZ58+qurFqU1Zowrj8J3o0WBTIpwOUgGkU0xheJdi6Bg4fRXGOejggq8YA9x8VvAnVob4awxBUWK+yKep/yBGsk40E0IJhQRqPpl+CvxSipl1ixYwrhB14pCW8zcE3H59BqJDICipjAHHhJtoY7C3Fut2tSwysotliQ8++zpzV1AS1EuM0zE4ixW4Az6CSaqoYlAxCeSCtON3h8o6MWSErKaOVY0pW2ZPga7da1i3E/6LZQACw2YdqbvA0LVsu6BJMSwL5KaFgMvLidn2psMl2CbUGEf2xlIqUvrPsuqfD4aCpvsoBoc0hXDBoGixN0H/eh2003BQ6A3RIZRlrBmipgxBhC0/xabFW5Eh39W4uGTXo7vpf6oOYnFJo2lW6CtIA+oZSOebDWLhzheQ/7Uuwok5cP+8XDGQssXRuO0bfPX5XettQcacrenm5H/0G9tsbQe75CsejYw4FNwtZM/ERB92RGCm1iHlKg==
    cookie_secret: AgC0Rq8zgCuLisYNSWZCzMOQO+Bk0QfsBZEazRV54BvT0i4AoLh2Bv7CFgycNfFbQdqHmsQKac1UxLbiVbHJYyn8ulfImhcgTuwSeL6hdPdsvs0Td536xjercakhVVTgR7HmeO3UWq1y06l+S0OI4ROHaYMzBM49hL+/I50Y4hlsfhXUsrdWV7aQuTKClCBXp/xGS+hN2686WsUO+QIQ10z4y54RLqzLgiNyZlqX09PPTkZ1ZTjc2KlmdY9nBxEpOQtPjp3eNyIeIh+J8rdqOOwaCDbkt0INQOkuk8kzFRy0ywfQnuA6zEHBJItGb8RGMZukd++awej0tX5Ot2eKWMSAduNMIYwtsoLn989MOniVPHzOeCq6m1aLkMNWDTETSGgMf7r4lRi36GD0p363KHl0d5UV3xacOhKE6ZULMiizXdKUAiW1/s9Z1HemfeZJAcMX3MWNBRwyd99nYbtQOLMFBozZ0KgBCon1bIjom+ShxbOqFqv3oSWOpiTAoBsgPhNfQMiZG7X/1tz5Mw69PAVDPkbNkkmCFnqEKdMaSmn+ka8yJvoCcMwygmTQan4HAz0qrfP2SR6nhPj1mTWzs3OaVui+o/8JCkFRtcpzhkeInk8U1oyv3BH1U5squdw2oNVnEBP5qmS18a4EHdsWar6P1+Vxp85lxxPgPfFasrBojPBMdRjILnZ1INAXx9YGWCt1MM2Uv6zokUGwDn3TgQmM01fHSNxYeTiIu7pw91VcLA==
  template:
    metadata:
      name: oauth2-proxy-secret
      namespace: observability
