apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: observability-access-policy
  namespace: observability
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: waypoint
  action: ALLOW
  rules:
    - from:
      - source:
          namespaces: ["observability", "monitoring"]

