apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: istio-system
spec:
  external_services:
    prometheus:
      url: "http://prometheus.monitoring.svc.cluster.local:9090"
    grafana:
      url: "http://grafana.monitoring.svc.cluster.local:3000"
