apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: istio-system
spec:
  auth:
    strategy: openid
    openid:
      client_id: "21513e26-a978-41f6-9713-1f1968617460"
      username_claim: "preferred_username"
      disable_rbac: true
      issuer_uri: "https://pocket.internal.czcx.cc"
      insecure_skip_verify_tls: true
      scopes:
        - openid
        - email
        - profile
      discovery_override:
        authorization_endpoint: "https://pocket.internal.czcx.cc/authorize"
        token_endpoint: "http://pocket-id.pocket-id.svc.cluster.local:1411/api/oidc/token"
        userinfo_endpoint: "http://pocket-id.pocket-id.svc.cluster.local:1411/api/oidc/userinfo"
        jwks_uri: "http://pocket-id.pocket-id.svc.cluster.local:1411/.well-known/jwks.json"
  server:
    web_fqdn: kiali.internal.czcx.cc
    web_schema: https
    web_port: "443"
    web_root: /kiali
  deployment:
    pod_annotations: {}
    resources:
      limits:
        memory: 512Mi
      requests:
        memory: 128Mi
  external_services:
    prometheus:
      url: "http://prometheus.monitoring.svc.cluster.local:80"
    tracing:
      internal_url: "http://jaeger-query.observability.svc.cluster.local:16686"
      url: "http://jaeger.internal.czcx.cc"
    grafana:
      # enabled: true
      internal_url: "http://grafana.monitoring.svc.cluster.local:80/" # Grafana service name is "grafana" and is in the "telemetry" namespace.
      external_url: "http://grafana.internal.czcx.cc" # Public facing URL of Grafana
      dashboards:
      - name: "Istio Service Dashboard"
        variables:
          namespace: "var-namespace"
          service: "var-service"
      - name: "Istio Workload Dashboard"
        variables:
          namespace: "var-namespace"
          workload: "var-workload"
      - name: "Istio Mesh Dashboard"
      - name: "Istio Control Plane Dashboard"
      - name: "Istio Performance Dashboard"
      - name: "Istio Wasm Extension Dashboard"
      auth:
        ca_file: ""
        insecure_skip_verify: false
        password: "VKE5kyt4fwx9xmq.zmj"
        token: ""
        type: "basic"
        use_kiali_token: false
        username: "admin"
      
