---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kiali
  namespace: istio-system
spec:
  encryptedData:
    oidc-secret: AgAhzyYT4KjcxgF4rJGYWOXAEWgAWrh3LgYrYXBcYWPIwICM0lDUtQlsXdITHHIdXpxdtFMSxpD+FaBIRuPU1XCyRnrELpQ++g2Id2hTjl978Y8Wy96bVLMAQSvLbYd85v4bs0pAenFiS4XScVhfr5mOVnb2uhLeQKxnLsc/MdTYTXY24gOMRMU/GgqiuADojoFqlnXLiS0QvS3AmY8B9jGAWAVhml7jc6h7UdCngO0c59owZKm4zoLLLQrIYvs6Ne+egf812cHh95xUP98nTAX6cDjeCvhSh+U1fCjd/iL9jHjKrah2tmZyc04sCEdm34WXsD362VxLXrzN+hc99VbuUlgsCwTj7J3cbYX+plvpBn2QoSqCq9uWfVt2wWUg22AIGd6CXevWgA5RfYzVy7zHFNqcax4f4sehiiuvkkSnIcQ8Wecd99clLbVfiACWPeB7Xig/hkQDU5RJC43xxzl47HnYyr0l0v7MSXQfIfZfCxugTygW6yKeogukcPFd/COcjhj8ozwDlBpdMrJ2aVSXOnEk8cpRsnT/8sgAr1plluvcinQtWSzSOBAS0EFpgPQV0hpXeh/+z1EIk8VPpNREpC3WN2NLVFq8x5wlGu4rlSnhdihyM0fm/V74wJ6g+lB33/+6FZKNI/bSCgNZSB3yXUR45t2DwVtifQT3PoQlRcrlkiz3HDuCQLoXAQBkMEPj3IfBQYXvSDhF67LFbXAaQQacBvoFlP2UjEU6luj9XQ==
  template:
    metadata:
      name: kiali
      namespace: istio-system
