apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: observability
spec:
  strategy: production
  collector:
    replicas: 1
    options:
      log-level: debug
      collector.zipkin.host-port: ":9411"
  ingester:
    options:
      log-level: debug
  storage:
    type: badger
    options:
      badger:
        directory-key: /badger/key
        directory-value: /badger/value
        ephemeral: false
  volumeMounts:
    - name: badger-storage
      mountPath: /badger
  volumes:
    - name: badger-storage
      emptyDir: {}
  ingress:
    ingressClassName: nginx
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - jaeger.internal.czcx.cc
    tls: 
      - hosts:
        - jaeger.internal.czcx.cc
        secretName: jaeger-tls-prod-cert
