---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oauth2-proxy-secret
  namespace: homer
spec:
  encryptedData:
    client_secret: AgAwnMpzDOMxU8wzwg5a78HemRvrJjHe3ZEjLEaQCcGeAb5QYBmtxgRvXelowzQCcby1x6VMJ/zRMCcrpj5eR+fuzXvf9gLFGwNCU4ETnmM/YoBWkaGbn9TLa+5bT8lXQqX0Tj1f/RbDlfyCsjj9vpKRWvcbzKZCjTej5keII2WO88FF/+XmJA6QEpxNyLoIRMd+sP9HOxwLFLnfFBJu3Oe3k3HbfrrgNTKP/GgKwzuERuwXNWoZ4/cIR2z13enldHNeJ17Vxd+TU2s0Rfiap8G6+enEJUfMskiQVx2nNj7XMbv0ydqK8zCvsEUC5kADgTKuP5Q0DKHsId4HmltbOyfb668T7++4QJiTm7LgLKRV0eiY0dNZKqcFxSweFV/YD0eLLWR2FZDkCw1KLc8d7vmun1v+3uIHzANCJAjNodwikOpoy09z/fVXn5eGJ5KiVtlzMEstlUqg7b1jS6kl3n5Y5ZF7HFADhkBj4935PNYwbJWkIdx6LJqIJL/mA/qdi7KYrQuq4kDtDdjzKuZlUc9Lq/DZXscy6qq6oo1aCYR/Z/+TQOz0SIkUXNeV4b2A938p0Gz6s/VsGCYLIXmxyBmjR4WY7cEOXYTAVk9Mb4B/DwOUsMDwKaPjk3UUArnKFNp6X6m902HLldGah/rwDE46bBI+thdAm3rPtOF9cMtxcNKL07mzSG7HC9K83P2fnme34sBJGfqOYpMwlIjmgzgefImPHH8Lr2Pyr0nc/SUWZg==
    cookie_secret: AgAju9ZXi0NAWFn+ibrrKdahzHgpkxMIE71ZL+owPNiTn1Dg3DXIFGC50/KA0ELdSFxMIkcRFuzraLfwPuEbHOrzuOOWCyoKO1HpQQ7B4hOTFmUodwwwJEtsB446BrgI76ceCldRTG3W3TEHK1HEZelc5Cu5lCUrmE/G4AluF6LEA8riM5KvsZwjoFVl7xhD//BiWiz1hwPotZ+Ws4Ddf9EuFiJELXJm9CD6DKE/3c4YN9Yr3r6UujlAsxuKHMWcR4pDDk4vRiNYAPc4PWMdoSVtMQlaq7wYbkTlPsjj+j6y/mMf5zFzf0QAgmurLNHj2Pp2jD+jyW4tR85V8Ji0EqnvWEPAE9kPmxxltJ1Bjoi3dIommm+gqUrUOJO9xIDwADJg4nj8mxoYLCy7mej6hWxUQjeCaaKoQlONwYWH48Rj+Ofe4Calq4tWhdhipMEK1O+tPjrj1h/+i9fYVIzEf2SywF29Pp79M2wVI+YxTHkb5mUG3U4m+JDZi6Z1kCnZ+Z0mMWQVa4WWtYzT8oitwd5/aMBkviVXEAt0kz+ITYQzhkYYPcr64sHpx64H5iq+CER9deTvkfnQbNXGxi4eGxU7nC6xzv/2hEDvpvCO92i3patlHYrncrSR2kJbAiefdUfNCAQRg/pBD521j6efy9RWAG18XCS0xH68FmYYI137TwXkRE+XTMWsbXGb0r76Qp40unUB846Xqt8VLLnNqM+UQPJDsltxhC3pwHXfgVNTBA==
  template:
    metadata:
      name: oauth2-proxy-secret
      namespace: homer
