apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-secret
  namespace: homer
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: oauth2-proxy-secret
    creationPolicy: Owner
  data:
    - secretKey: client_secret
      remoteRef:
        key: homer/client_secret
    - secretKey: cookie_secret
      remoteRef:
        key: homer/cookie_secret
