apiVersion: v1
kind: ConfigMap
metadata:
  name: homer-config
  namespace: homer
data:
  config.yml: |
    ---
    title: "Homelab Dashboard"
    header: true
    footer: false
    columns: "2"
    connectivityCheck: true
    theme: default

    colors:
      light:
        highlight-primary: "#3367d6"
        highlight-secondary: "#4285f4"
        highlight-hover: "#5a95f5"
        background: "#f5f5f5"
        card-background: "#ffffff"
        text: "#363636"
        text-header: "#424242"
        text-title: "#303030"
        text-subtitle: "#424242"
        card-shadow: rgba(0, 0, 0, 0.1)
        link-hover: "#363636"
        background-image: "assets/your/light/bg.png"
      dark:
        highlight-primary: "#3367d6"
        highlight-secondary: "#4285f4"
        highlight-hover: "#5a95f5"
        background: "#131313"
        card-background: "#2b2b2b"
        text: "#eaeaea"
        text-header: "#ffffff"
        text-title: "#fafafa"
        text-subtitle: "#f5f5f5"
        card-shadow: rgba(0, 0, 0, 0.4)
        link-hover: "#ffdd57"
        background-image: "assets/your/dark/bg.png"

    links:
      - name: "Kubernetes Config"
        icon: "fab fa-github"
        url: "https://github.com/hugomd/kubernetes-homelab"

    services:
      - name: "Networking"
        icon: "fas fa-server"
        items:
          - name: "NextDNS"
            url: "https://my.nextdns.io"
            icon: "fas fa-book"
          - name: "whoami"
            url: "https://who.sost.ovh"
            icon: "fas fa-user"
      - name: "Monitoring"
        icon: "fas fa-heartbeat"
        items:
          - name: "Grafana"
            url: "https://grafana.sost.ovh"
            icon: "fa fa-exclamation-circle"
