apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homer-tls-cert
  namespace: homer
spec:
  secretName: homer-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - homer.czcx.cc
