---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgAjySG6seVIhNzymuopfF8bg9ulewXKCmsegFK72ABh5xKnYWxXMSQm0XPRGZHE0daSkPj9k9QA+H9IOshAopEBcGY/GoiGAck8w65l3PMwpdwC4cq+uRQaITTzsjWDZr4bxWf0oRGdArzEDvY55YeB6UULB0a23GI3e4gR0tFF8E6McqXQ53mnmoyh0oRZq4GBb23OHVweK+cm9l8nR533BaFwwgIiW7T9QWNbGQ/IUrBjrkUaWZXFVLLdq3bna309H/bat0zml3KYqt1JB5CYpipF3MCOizfrsjDa4uS5ADeI9MXyqHXkELv+RgS23W0Tp0/VyXD6FrbF5W2TiResTyH+nIcbkI6t/QWiwGAuedmKO+X1AAnj7AIRqCtqQFHmP1gMyfebhdS4B/hDVDUP/qGjWnpyeN/2DNb6TU7pTd0dwPQS0Kl8saNuXNecKYW7KKjqyD+euOstDE+mwyUEYA27wDsTLPN5TsKiSUQrlzTERQKhPPARaIdtF6h1+sZD2H5thTDlJL5Q3LmgG61jo1VogZ2L+GD90zWAuLNbzZ9MaqCIL0OVWG9us11AKo0q7bFO7CCxn1Ix++4eCR868Q3ZwLHUGv6QycMLm6huaFCafqW0G5wiWWwprswVuhF3fI0VQKFJPFEhof1V8VHPIkxg7W88ME58VE1zhViyf5S+6NWLq4B2cWHAGoT6EMe7pe2mSWHyXn7o8IUef4yzlS5GZu+WzPjMDz8k3Tj0IGA2xQm1cZHaXEcdVOMLKBo9u1YOnK+Aunna/JLkLMb1ED9Q15p3XhNeret613ZtFmYWik8ZXhE3kQK6UylVKKMYZU2OzGtG2hG0JNYHmB/efCyN98znoEz2tV0VXNtB9T4RzLq0rCEXb0z0XGE0gwfcv8M0570XqzWdJvHqggqWoVBaNWb76ItJpXtTEm6F8XpplJAFUG1v
  template:
    metadata:
      name: cloudflared-token
      namespace: cloudflared
