---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oauth2-proxy-secret
  namespace: monitoring
spec:
  encryptedData:
    client_secret: AgBUPQgNieWqregLF22Q+qnl55611MphpIpafYi9FRtvc5eEEkeJ36TegEe4aA7z/UncYlWawF6VGhr2Fp+ipzDbYRPUPx7ld9CNh3bXig/hbYrfEbVAySLMKtuVFrJG/pQXvp9RNx8Yp6AFexWdqZ7TGgrOa4WP2i58zoKiQ1NtEyfZOFhxVnt9IByEniX8XVYUbIJGDsjUztNPOkT2TFSCxEOG8jDX54I/nugjEMZEKEg4IOVN0UCpkfyKeNZEZ1eUDH3DDYqCkido/cA8zsTCIdOh21MrAUf6eFIWGAkvbbvGnS2itpCsQ1HotLnNycawpKQaxpyge3xB9pOWAZ22TTW7CYfQ7IYQB1qST3Lt2Jfhao5nX0MoPjIsUtWxTIcPiBy850FDzHXgzSPBd2I3V0v1juAkaHC2vTwD8oaiRrDUSRgzPELBnYeNnK6zb4UZJ442Ph64yz1VFIRVev+vITJPksJBL9U2tzX943e/i4954naZi6nLXE9imntzucNk4OyASMkgVCIdwGRfS5qEs7vjt7g02CHJdapoUYVxlLuQ89q7p4oKuxBvj+CRR3V0XK6qQfbCKzBtY/CA+WHIix3doraPHb6YS289ITYlDQMKrFN4hFt1+itWt7ara+Ztgxt2nY0mSq6QPPs2KBWrNGOPCc0TWZEgLZgrKBT3ctcNxQ0Khonb3Qn1PWXbe1zI6re0qpcHMzC/o6nbk+XXAN/XvOKHGYfiLfCQa6Wq8Q==
    cookie_secret: AgCHSu+sQ3C7SA/QIGxYHiBfEAagXW4H1bdjtEaS8YuJbbCWuxvLJmflSgC6llJIsZYA4IAmLla57YGmj/qvxXOvEml7OpmlpjBOpbN5EgLpPgJSILpg7nfiPHlLWlHpechYatiaRAeNdL8eUcmMvKcz7RvUH/Wupn5SIsXJp3dynq1KQ49tTBpCWf6BY+KCboi8J5ZrFskwCJX+3JFQYvPSVCLd5G0uNRFLqe9TPKj+TKH25wxFO96MbX1KpT/jXq09m8jD8F5AkeXPHmokqF1qpIRw3O/c4o16qnT0gYYlSzNnoB4jppTRbhmSsw96WB7FRNuenHeddlq+RB/BwDqa6y+6mynsqGrSrB+ApVEfV6w3Gu3zga/hMrmKAaRuLe4/3D37PMebTjeVTsNMZ1nVecR/x/5CabDfBGBMa1PbGBEhQbfyJ4z2eK6WHdX2nSPPcR7K1nbT2kTriGKM+3YliY3Si/j2Ep/lEmUA8rE1sksbkZeQuqo6mYgGyXiYTm8jiKh2txuiKcNnkp8uq12EWfskdCuUOPKV0HQOPzviw8awHTte/64BUyizC7jqSguy4iavn1FaKQB2DEVjLfynNev3xmfmq0Rn7cLkg9yVIyMM7KsYRFCfdZl15ozU6BncUHlioa8MZrMCw+mpPoeZ3ih1tN/ecMVU5+qSyqAQp4Hf5d4SZo9LoFkgySNOL7JG1RweYkwqlqHhw4CuTpD86Y4gOdOYGHslXoSG5g+5MA==
  template:
    metadata:
      name: oauth2-proxy-secret
      namespace: monitoring
