---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgB3MRDlIXgXiwTnbQ60aRCv5iu1HJUhyFW2LZsLymdd9gIHdl/Vi7MVN2doKxIB38CRrmS+kUM9OvfNLqYwtJUrK6ig9A+sSNpJzGmpcmkeFuVp7R3RaQu+hZ1zsDZqg3zeiemym6qpAW2S94bs2yJmPEJIsis5hIt7a4L5XtXgc7Q5iZwn04+8SM9lFNQoChcrQ3pA5U7Oyk+CKOKc+jBdmSZts2JN4dyeRrxQsBdt41s5EDKA3BkSF2qhJLRFAukEmde/4dWomYSJ0phwRk5HjBgWakfDABL8WizsibG6anfm81jQVFexxpmBvMmvf7oUe3pQz3H74MbDgfZiztfoTLBgu9DArHOC0nKfVgl7ccTcB8lsxVXyZmHzHnSo+Fb/jvkYQEAtCM0guC7NwbvZObK44MTFnfQwhiDqMB3AU6PKgeOkkez7F8ehePiOWOf/0uNKGmyZjlngsI6Cw19dMkhwu0sqeNrcDYpdStwvbD1XpCXgIiG2dlZ/pzaD7JFEyAwI4m7cw6lb1T0UXdIGnTEoJ19JGL7f7wUJ9gRC6CJE7srV8cTmuLTfyVOGIsjDsQjrAGxf5EKdQupld8U0QIuMbQ8t+0yoKfTEUTVnMo8/de9j7GZjqZ8yRqwi/cacrdTELSCnLurzMMAijKda7el0a7usjKnRJ/hodapZFNquLDtMQmaj+9VtIxAXsDkPfwZkCzPu98SmWf8pvB7Nog==
    client_secret: AgAvfkULEK1M/It7rbGJB7QHcRVdM830R8MB+FN25SKqSqu23Q+byRL4CoXIINxTow5yxrXYNSlVS72MPs+xwabqNbkopzIsBu4YyG7OGifUkykt5U5oZyVZ/VXBmFH0U0T7Tv2vNSPaY2eN9nyfuLDOPUm6kbgZ8aDgcWxGpHDUcL3+6QLR3VwVWDNjH0Sy9mWaxybCotfvKRH80d81VBLFq+ZFVl/Sqr7+59xxnSEsocoqIm+zmxT8Hy6DbILS1lQhzEu1ciwfeiL8vgIoFcXCUqyIxssWexpq0yhfmJcFrvWstloqOwR2ODddF4/Crw+AkXyfpGzunxUwDinREJhmpBNRDEzdUgnt5VD8eNA1PA8alh9EQhlaBgwkFId2Xterx3yvD3T/ZWUh7srxdUrO2jyZQfVv2Z9f1hBq3g2a6zRNgpvAbeGYEAYc7sfLXmsImEDsBgpt7vcTbuDZdR5cQCZZWVj05hGvr+Fup0lKugE15ysx0D8qYWZEI89cP5JgA6pTJto4oTniI2Btl+6UwARE58pCS2e9RY6OYWOuwoe3jIe78qBGU7FPXPXiOXxLBrbH/Ilwk46fNS12UsADhdw9VuB0K9A6cjHs4RsKUdMYUL+cuquaaDycMBpCtVj8BRzRs5/txYTixoVNJAB6j5iAS06qpB9CnR+DA+54SVHonLOWzYYdHjZloGe4Z2Aem71HDEPf+VjzYH8bCau8OcXR8wmeB0PcYGODFVEipcHP8FY+IzbVeXOEcg6BsvZOPLBg7cQrnB0NFY75zTnS
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
