apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-pv
  namespace: jellyfin
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /volume1/Anime
    server: 192.168.68.52:5001  # Replace with your NAS IP
