apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  type: ClusterIP
  ports:
    - name: http-jellyfin
      protocol: TCP
      port: 8096   # Kubernetes internal port
      targetPort: 8096  # NAS Jellyfin port
