apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyfin-tls-cert
  namespace: jellyfin
spec:
  secretName: jellyfin-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - jellyfin.czcx.cc
