apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale-proxy
  namespace: tailscale-proxy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale-proxy
  namespace: tailscale-proxy
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["tailscale"]
    verbs: ["get", "update", "patch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale-proxy
  namespace: tailscale-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tailscale-proxy
subjects:
  - kind: ServiceAccount
    name: tailscale-proxy
    namespace: tailscale-proxy
