apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tailscale-proxy-state
  namespace: tailscale-proxy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
