---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-proxy-secret
  namespace: tailscale-proxy
spec:
  encryptedData:
    TS_AUTHKEY: AgAxPpw2O2CXoPL82JMXPUGdDxxkZSMaMkAlsp4z6EFkRSQLfo9Ptp0xv1z3lokZ33AJvyW5b655F/3WeVMhpgGpUTYpB1oKTehWKTuI9MTe/aFFHICdxg2HoRLmc1VOwlx1TA6LYGSJRuDQwpZ7ZFTEp1wwkVtb8iVhczK+fmm9gkUvqVPFAZuxZmuBBlayIHs6wfeeRvGpoHOYDnFUTD6vQqD+qc5xIADeTPsxHq37a/vB1ah5ComkVIwbvqDxfhkOaB8sI5Qttrcv0p+92Lc57N0ORM5k9qi3EWtcbhZLco/EtZZO7JC01/lGHiXrQAwUHESnUq+7h/Em7PGjfbUzlkmHCdKMNbuzfuS4a2evQhl9ymLAmQohuwsKbIadRQgMxlZRz4hod+W8ZBDAkj6cr11eMTuNOD/gglvFW1eZfZeECoiVM+Qq+ceTN8n+arEaJXowtbd5rkIXUfYer2704ltY2hAPNMH4ZMCjjvNj0EfA1/WiaXcziCYOQGsahSdilq/22UZC+H3owHlLc8XWkS6UA3O0mZeYt1viCmzo/arif+N1OuLYBzvARcPJIcrUkwOrkh7zxvgiVIVMV2P/tk6lkmsrehuDQm1P2i89Yk5IiXCewY2bPNxBAGxgJv2PJUj7xkpJRWhTJojB4tX4NeTpUXRWexZuX7hIxoHy/+t/2rfBFg+Eg8RF/XuCasmiQY9pL/lM/lrqbe1kOa3ln8S5X8iipXwnGHHQklLD0jli7+DX0AGrbE8cCBsYIsvRyXjqxD5VN008UvIMPA==
  template:
    metadata:
      name: tailscale-proxy-secret
      namespace: tailscale-proxy
