apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-proxy-secret
  namespace: tailscale-proxy
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: tailscale-proxy-secret
    creationPolicy: Owner
  data:
    - secretKey: TS_AUTHKEY
      remoteRef:
        key: tailscale-proxy/TS_AUTHKEY
