apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lesma-data
  namespace: lesma
  labels:
    app: lesma
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
