apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: affine-secrets
  namespace: affine
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: affine-secrets
    creationPolicy: Owner
  data:
    - secretKey: AFFINE_ADMIN_EMAIL
      remoteRef:
        key: affine/AFFINE_ADMIN_EMAIL
    - secretKey: AFFINE_ADMIN_PASSWORD
      remoteRef:
        key: affine/AFFINE_ADMIN_PASSWORD
    - secretKey: DATABASE_URL
      remoteRef:
        key: affine/DATABASE_URL
    - secretKey: REDIS_SERVER_DATABASE
      remoteRef:
        key: affine/REDIS_SERVER_DATABASE
    - secretKey: REDIS_SERVER_HOST
      remoteRef:
        key: affine/REDIS_SERVER_HOST
    - secretKey: REDIS_SERVER_PASSWORD
      remoteRef:
        key: affine/REDIS_SERVER_PASSWORD
    - secretKey: REDIS_SERVER_PORT
      remoteRef:
        key: affine/REDIS_SERVER_PORT
    - secretKey: REDIS_SERVER_USERNAME
      remoteRef:
        key: affine/REDIS_SERVER_USERNAME
