---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-superuser
  namespace: postgres
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgABb1VI1FZiFX5tWYhJl5DRJoKO4I3Y6V44VMv+BjoBk3t3Njqan84zderM3gnR6o0OCjAe212AsO6WaBqLgDHIbadB7qk5kebq0f1scV8GOkx1a4ixWqER2mgFJQXY607wVAvp4ERdP1jf2dnjA7k+kQnolIyPCi24dlGj3Ikvhv3ML769NaUwdq5lZFEbHE+nX6XkXBO6bARWHbiE10px2beEAzpdPEOEBrBCDvKN4NiYXY6JpdsGsSuJk9oJ7v9lnnEPJaVClH4jw3pHQ0QeKpoGjzo7sNjr0y50JSVN0CTfOMuxIL3tw8kxJNXnxmfCWBmHHBoIOPmFNI7l6ekZK+G8ITdEZX3ffuZZhFP+FdyDejlTZP34l7OFFzyrxZI2pIAvdJjZGiL8KQWCpO5S9mx6HgSMOtFgogRhpRVvnTrPUoIOa+URu2nuAaqf5GjQii8cnOo/uPjivdGbcx+SF8Ejm582ihG+0b2TLhOMXgUiDE35kqNjOrLCa6xm70b/l8nFnMZR7yuq6W+V6p4hBuPhi8t64UmpDdFqqEwGKi4KxdgEDx3L3j6rhnnHbXrwyeetm1PO98qH+oqCSk0Vh6kBulGCfTzexCdsYwhBWiGcbqisRBTKZQPPBtAmVI7j4SpT+K2A8AtzPjlDg5M/xPxcJRgG2fscqV/XBxyV3J8i5/QZco/K4ReS0YAFLeK+LaZFHZZicdrsUEt5ikin
  template:
    metadata:
      name: postgres-superuser
      namespace: postgres
