apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-superuser
  namespace: postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: postgres-superuser
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: postgres/POSTGRES_PASSWORD
