apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-backups
  namespace: postgres
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi
  # storageClassName: local-path

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: pg-backup-pvc
  namespace: postgres
spec:
  schedule: "30 2 * * *" # daily at 02:30
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            job: pg-backup
        spec:
          restartPolicy: OnFailure
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: statefulset.kubernetes.io/pod-name
                        operator: In
                        values: ["postgres-0"]
                  topologyKey: "kubernetes.io/hostname"
          containers:
            - name: backup
              image: postgres:16-alpine
              imagePullPolicy: IfNotPresent
              env:
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-superuser
                      key: POSTGRES_PASSWORD
              command:
                - /bin/sh
                - -c
                - >
                  set -euo pipefail;
                  TS=$(date +%Y%m%d-%H%M%S);
                  mkdir -p /backup;
                  pg_dumpall -h postgres.postgres.svc.cluster.local -U postgres | gzip > /backup/pgdumpall-$TS.sql.gz;
                  # keep last 7 days
                  find /backup -type f -name 'pgdumpall-*.sql.gz' -mtime +7 -delete;
              volumeMounts:
                - name: backups
                  mountPath: /backup
          volumes:
            - name: backups
              persistentVolumeClaim:
                claimName: pg-backups
