---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: searxng-tailscale
  namespace: searxng
spec:
  encryptedData:
    TS_AUTHKEY: AgBliND5GCltyVAhPSH8WywSFXJqdrQmAtFCka3mUJinO5duYdsZcCwyFRjKDXRku9sQ4wyEgfxxUHZATUSxcsuxN9KATuCuzyVVDceVTL7p4rR+/1oG0btJMvfObhOnUNspAgcyYQCnnMN1gknYv+fP3a/GUghnnPKNmeUkMFe0+SORIyBqSohv/JI9rnhq/X3BezgPeXNVAApF4k8H3HTSqn2e54yQfpq+foWn5hggs+4IChxM7bOLXsgMgo6J2ExWioevdrWtc0AriZ5/um4Hd8gTNH3w0oph9tauvnc9gmtqrZe5Jt3aRDptS2x6oTv3InUBf/PQcqO7FbNOkJI0UsnPe1ed/zHK65ZKa6wOi2oNOAdnBuNkG/rdMWQ6dwJMxizPC3Tqm7QdVquHVXjmaSxOWJkniwK+nnp17xYbD+6jqv/fKfr1JEc4jyoy8iabalCoNaKs1tXrvGOq4eh806GWKV63H1tRCWNuNQY49RGZIRm8vM1pmLEpLEPe3RAMU6j2Hakq35unByCOmXUKIY3TRrswI4eiuBrzh+YPkBFgLDeqOJ7JwyFK2qev+QiuUQ9Jnlsa4IcAN8Axbx6wgKatGpEiIEyoAwxnv9Du6BQRdm275bt+A/xJShLFmHT3olZKXmqdiMtsmC7/ljeHOO7yefwMq6Ca8ch7/Of4LfOJ5kqMrEdsqR/vXpppOKOncrV1rNNq2Lmqjs+facAyb76mJ2c13OlvGG5hltt3J11/V8LKBjppukpl09HH8tlpL1yJZNioIziuclnf
  template:
    metadata:
      name: searxng-tailscale
      namespace: searxng
