---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: searxng-secret
  namespace: searxng
spec:
  encryptedData:
    SEARXNG_SECRET_KEY: AgA1PDM9F7wpeJL8p4jxhC4FnUVoLdCsyrq6oj9b6pVQ494OJg2fvPLhIKiuEqAztu2ytbyTFBnv9gpCyMubDbcNwxdTPfeFdLsQ3+0C34qTUzla7ptvQCl5EmsNnzYFNW2uTeZZamm+VOVbihvW/rLPp/ViBtWT0s9FrVwzh2evJF+0u804HZagZvMB9rTXn6Hw6tAXc7fcAiMgDJBDOAydonh5aHYofeBElWVoV49Xffb2/X08cnfL3S63Z+O7UuOcDCRpEjFu5FLHD+7X4B0Q7Yl2Ht9E91p7QxXfGqeMcOK9HqyZG6Y6wV/uXwGf+EyOWr6jfQagSaT4KEVaeoWmII1ktalam3geZKdyz22gFPNt1Ad2uGqViWjBXCgiOPV+ZLh8FsPooC3sDzPU3rnfUH9qqKGOyIUrs2tfgXzIq1BQR0VFs52jIfuQ+jpo0b3ylSXrbSyIEtg51+eAsUO0PIUeuwD/PTemFq0SwQwjCgsQ9ahqenyBiihreiXaZ0TqtBDw4oLYUxMxbA58MPmcJKDHAxOZG8dAZrT53JIODRr/usXs6EdMol3fcvx7Hg/6ZJgn0y/8hJIqiJa0q1MSY5q3bHVGdUXo+fDb4fO79nQuio6EAh9IRnU5JiImzTxj0MYQpqD65p4OzZsqsEwIh28yGYYkSQSBO+AnHiFzl3h3TSAzi4Lh/IElAcIMPWnVlBhqEcFEgr6Qjy7DiFjfhbIV0ImXdXyJHLRErzrvx6RRAm6gOCTduOrS2sK1BPA1SuQemaF36N/d+7FQbHiV
  template:
    metadata:
      name: searxng-secret
      namespace: searxng
