apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: searxng-secret
  namespace: searxng
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: searxng-secret
    creationPolicy: Owner
  data:
    - secretKey: SEARXNG_SECRET_KEY
      remoteRef:
        key: searxng/SEARXNG_SECRET_KEY
