apiVersion: batch/v1
kind: Job
metadata:
  name: monica-setup-production
  namespace: monica
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: setup
          image: monica:latest
          command: ["php","/var/www/html/artisan","setup:production"]
          env:
            - {name: DB_CONNECTION, value: "mysql"}
            - {name: DB_HOST, value: "mariadb-svc"}
            - {name: DB_PORT, value: "3306"}
          envFrom:
            - secretRef: {name: monica-app}
            - secretRef: {name: monica-db}
          volumeMounts:
            - name: storage
              mountPath: /var/www/html/storage
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: monica-storage
