apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: nginx@cassie.id
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx
          solvers:
      - dns01:
          cloudflare:
            email: "me@cassie.id"
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token

