---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBiNFNvCTMm1ekp9HVmGn3WEbhsEcI0VOWBMRyi+5ucvULCpeXuu/Iyi9kcGTuEKRdyNUkhN2YA+XdaLh910iZU7AKB1P4Q/RXVjqpXiM+9uKZOuc17z1IaftL3Cfa7DWwM/8wgdtmfCCFnIciFekBTVtAtb/LC5Fv7c673e/XBgIpK/3uJDtZuE6qVjE3L7WjvgPI0cuhAFMrhCzrDZkqRrJUt840a5Xvna7x0In9yfaVLh1+YEojjrnJ3+gs+aHh4qqgzhTmuqEjkO92wWUF2IroX31d4XiOHEMBhwNJr875qptSP9Oog6ugMW8LkFIUcKAS8iupaYElFFFQPoDlPxotiLkN0/3AwTP4uruO3Aef7vjd6o3R4vp5eBhFwL4lhP6/56IZ6WqpW0DcJdSy1vxrAqNML7WtfsbLsxro1icTNwGVZhN1nVJXs8nXnJ/BjBkU309fE+ZlevmJBQg2x79Qgv3tXuCmXFWsDQW1ddhf2me5wRWs2hJS3zzOGDXcxDSm9jP1UQU4z7QJzOtEptcN9zsJ8xO56p7pvdWIvO0wXYzrZQXoY8eEmcUqn8hegm5w+d7b5PptDQ3x79QpDm5rfUhSUjM8+vSWisP3HEmF+QM4yTDi7evXCzcmKcbxTDaA8ZbVDaPfUuOwJWFLW9+Sj3AZHWE4BuIjApnqSIJUWCEA/fTR2Q0NVvbpHLGcJDc+PP+FTh8QLE2bE61QsYDCLRst6R3FGOG09s9fMvve1/gz69wN7LGwe54tPvWKMzYB9RQ==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager

