---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-auth
  namespace: redis
spec:
  encryptedData:
    REDIS_PASSWORD: AgCZg5I8xaqZi8Z+olj3pAlmVi9Gg0M01bN+L0bB98fXWWRjiwNzd1w1Tp48JLH6PC/1RgMxR2WH+56fvHMs+WLXnn+CAiizn0/bGPm6o72rJOr+k++4jzj0X1Jw17lNA2WTSVHgJ194c708BMqfUR2rnRp+XQn/BqZyk8gCDRodVWFmVbHMfTgHbP5oU3qU5KuzslQMw+ysqI5FgRboLDXEKgMSzzx98hHgG7vyxoDoG3fadIfgYKzfG/q4S5xUFoZyDlCzjn3J8mBBADzEDTKGIsmccGvBp1Wm+wb4DEvq8Tw262m/noejMJ7Egq6eVJJ7PFgHTgfVRnifaD7+3bnymmJI5BuykCswFVOaUg3BmT6q8NVk4HcEYH18uX9a9GXMN7IUTB3xgDzPqRMzXb2L8mYLMex04uw7K5B1Q9tZYAo/+tgxEqFc/4lFtpQjkPUKuyhgl3GoQzfIZqwuV+wzPtG/KqGuIRHUL/vl8/7SgTg2xZXgWzIWI8aZsfZ1CAbGgIl/GgpL05ZI4OolRb9LHWuS0D61KFdhB68YCjISr7GOSfOHGHdVBeQyOfyKX12UChyR+v0X3cUUO2bDwVxktJjyq//xKFZPFx0Af4Xb49ljUd1RBSszQaJOdxAmqLaH9Xg7xU2pkx75sZiGo6jm3lDes8e+7sP+onKhsdNXd+cTTkILg2kBMqK0Z4JWNvOTrvOGMXjqy2Q4nrEoSXH+
  template:
    metadata:
      name: redis-auth
      namespace: redis
